//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.ProductAttributes = new HashSet<ProductAttribute>();
        }
    
        public int AttrID { get; set; }
        public string AttrName { get; set; }
        public Nullable<int> AttriGroupID { get; set; }
    
        public virtual AttributeGroup AttributeGroup { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
    }
}
