//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeGroup
    {
        public AttributeGroup()
        {
            this.Attributes = new HashSet<Attribute>();
        }
    
        public int AttrGroupID { get; set; }
        public string AttrGroupName { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
    }
}
