//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.ExcludeCoupons = new HashSet<ExcludeCoupon>();
        }
    
        public int CouponID { get; set; }
        public string Code { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Type { get; set; }
        public Nullable<bool> FreeShip { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> Indefinite { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<ExcludeCoupon> ExcludeCoupons { get; set; }
    }
}
