//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcludeCoupon
    {
        public int CouponID { get; set; }
        public int GroupID { get; set; }
        public string Description { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual GroupProduct GroupProduct { get; set; }
    }
}
