//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menus1 = new HashSet<Menu>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string Link { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<byte> Priority { get; set; }
    
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual Menu Menu1 { get; set; }
    }
}
