//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.ProductOptions = new HashSet<ProductOption>();
        }
    
        public int OptionID { get; set; }
        public string OptionName { get; set; }
        public Nullable<int> OptionGroupID { get; set; }
    
        public virtual OptionGroup OptionGroup { get; set; }
        public virtual ICollection<ProductOption> ProductOptions { get; set; }
    }
}
