//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionGroup
    {
        public OptionGroup()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int OptionGroupID { get; set; }
        public string OptionGroupName { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
    }
}
