//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<byte> Quantity { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<long> Total { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
