//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public int ProductID { get; set; }
        public int OptionID { get; set; }
        public string Value { get; set; }
        public Nullable<byte> Priority { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Product Product { get; set; }
    }
}
