//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public byte[] Email { get; set; }
        public Nullable<byte> UserRule { get; set; }
        public string IP { get; set; }
        public byte[] Status { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    }
}
