//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public Ward()
        {
            this.Customers = new HashSet<Customer>();
            this.Orders = new HashSet<Order>();
        }
    
        public int WardId { get; set; }
        public string WardName { get; set; }
        public string Type { get; set; }
        public int DistrictId { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
